CREATE TABLE orders(
    id SERIAL PRIMARY KEY,
    user_id_ INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id_) REFERENCES users(id) ON DELETE CASCADE
);
